server:
  port: 8082
spring:
  application:
    name: post service
  h2 :
    console.enabled : true
  datasource :
    url : jdbc:h2:file:./data/post_service_db
    driverClassName : org.h2.Driver
    username : sa
    password : password
  jpa :
    database-platform : org.hibernate.dialect.H2Dialect
    defer-datasource-initialization : true
    generate-ddl : true
    hibernate.ddl-auto : update